version: '3.9'

services:
  app:
    build:
      context: ./docker/php
      args:
        - TZ=${TZ}
        - SSH_PRIVATE_KEY=${SSH_PRIVATE_KEY}
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - TZ=${TZ}
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_DRIVER=redis
      - REDIS_HOST=redis
    volumes:
      - ./src:/var/www
      - ./logs:/var/log/php
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/php-fpm.d/zzz-www.conf:/usr/local/etc/php-fpm.d/zzz-www.conf
      - php-fpm-socket:/var/run/php-fpm
    tty: true
    working_dir: /var/www
    depends_on:
      - db

  web:
    build:
      context: ./docker/nginx
    ports:
      - ${LOCAL_IP}:8000:8000
    volumes:
      - ./src:/var/www
      - ./logs:/var/log/nginx
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - php-fpm-socket:/var/run/php-fpm
    environment:
      - TZ=${TZ}
    links:
      - app
    depends_on:
      - app

  db:
    platform: linux/x86_64
    image: mysql:8.0.28
    volumes:
      - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    ports:
      - ${LOCAL_IP}:3306:3306

  front_app:
    build:
      # context: .
      dockerfile: ./docker/node/Dockerfile
      args:
        - TZ=${TZ}
    volumes:
      - ./src/html/client:/var/www/html/client
    ports:
      - ${LOCAL_IP}:3000:3000
    links:
      - web
    depends_on:
      - web

  redis:
    image: redis:6.2-alpine3.15
    volumes:
      - redis-store:/data

volumes:
  php-fpm-socket:
    driver: local
  db-store:
    driver: local
  redis-store:
    driver: local