version: '3.9'
# volumes を定義する
volumes:
  php-fpm-socket:
  db-store:
services:
  app:
    build:
      # contextでDokcerfileの場所を指定
      context: ./docker/php
      # argsを引数でビルド時に変数を渡す
      args:
        - TZ=${TZ}
    # ホスト側パス:コンテナのパス
    volumes:
      - ./src:/var/www
      - ./logs:/var/log/php
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/php-fpm.d/zzz-www.conf:/usr/local/etc/php-fpm.d/zzz-www.conf
      - php-fpm-socket:/var/run/php-fpm
    tty: true
    # コンテナ実行時の作業ディレクトリを指定する
    working_dir: /var/www
    depends_on:
      - db
  web:
    build:
      context: ./docker/nginx
    ports:
      - 8000:8000
    volumes:
      - ./src:/var/www
      - ./logs:/var/log/nginx
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - php-fpm-socket:/var/run/php-fpm
    environment:
      - TZ=${TZ}
    links:
      - app
    depends_on:
      - app
  db:
    image: mysql:8.0
    volumes:
      - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    ports:
      - 3307:3306
  front_app:
    build:
      # context: .
      dockerfile: ./docker/node/Dockerfile
      args:
        - TZ=${TZ}
    volumes:
      - ./src/client:/var/www/client
    ports:
      - 3000:3000
    links:
      - web
    depends_on:
      - web